language: python
python:
  - "3.7"
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - "uwsgi --http :5000 --manage-script-name --mount /=main:app --daemonize=main_app.log"
  - "curl http://127.0.0.1:5000/healthz"