---
apiVersion: v1
kind: Service
metadata:
  name: dad-jokes
  namespace: dadjokes
  labels:
    app: dad-jokes
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: dad-jokes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dad-jokes
  namespace: dadjokes
spec:
  selector:
    matchLabels:
      app: dad-jokes
  template:
    metadata:
      labels:
        app: dad-jokes
    spec:
      containers:
      - image: yesinteractive/dadjokes
        name: dad-jokes
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 80
          name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dad-jokes-ui
  namespace: dadjokes
spec:
  selector:
    matchLabels:
      app: dad-jokes-ui
  template:
    metadata:
      labels:
        app: dad-jokes-ui
    spec:
      containers:
      - image: nhjay/dadjoke-ui:v0.3.7
        name: dad-jokes-ui
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 9191
          name: stats
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
---
apiVersion: v1
kind: Service
metadata:
  name: dad-jokes-ui
  namespace: dadjokes
  labels:
    app: dad-jokes-ui
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    name: http
    targetPort: 5000
  - port: 9191
    name: stats
    targetPort: 9191
  selector:
    app: dad-jokes-ui
