version: '3.6'

services:

  dadjokes:
    image: docker.io/yesinteractive/dadjokes
    container_name: dadjokes
    restart: unless-stopped
    ports:
      - "8100:8100"
      - "8143:8143"

  dadjokes-ui:
    image: docker.io/nhjay/dadjoke-ui
    container_name: dadjokes-ui
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - data_url=http://dadjokes:8100/
    depends_on:
      - dadjokes
    healthcheck:
        test: curl --fail http://127.0.0.1:5000/healthz || exit 1
        interval: 60s
        retries: 5
        start_period: 20s
        timeout: 10s
